[PROTOCOLS]
Immunoinformatics = [
    {"tag": "section", "text": "Imports", "icon": "bookmark.png", "children": [
	]},
	{"tag": "section", "text": "Epitope management", "icon": "bookmark.png", "children": [
	]},
	{"tag": "section", "text": "Epitope prediction", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "B-epitopes", "openItem": "False", "children": [
	        {"tag": "protocol", "value": "ProtIIITDEpitopePrediction", "text": "default"},
	        {"tag": "protocol", "value": "ProtScanNetPrediction", "text": "default"},
	        {"tag": "protocol", "value": "ProtDiscoTopePrediction", "text": "default"}
	    ]},
	    {"tag": "protocol_group", "text": "T-epitopes", "openItem": "False", "children": [
	    ]}
	]},
	{"tag": "section", "text": "Epitope evaluation", "icon": "bookmark.png", "children": [
	    {"tag": "protocol", "value": "ProtIIITDEvaluations", "text": "default"},
	    {"tag": "protocol", "value": "ProtVaxignMLEpitopeEvaluation", "text": "default"},
	    {"tag": "protocol", "value": "ProtTMbedPredict", "text": "default"},
	    {"tag": "protocol", "value": "ProtSignalPPrediction", "text": "default"}
	]},
	{"tag": "section", "text": "Multiepitope management", "icon": "bookmark.png", "children": [
	    {"tag": "protocol", "value": "ProtEpitopeConstructAssembly", "text": "default"}
	]}
    ]
