[PROTOCOLS]
Immunoinformatics = [
	{"tag": "section", "text": "Epitope prediction", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "B-epitopes", "openItem": "False", "children": [
	        {"tag": "protocol", "value": "ProtIIITDEpitopePrediction", "text": "default"}
	    ]},
	    {"tag": "protocol_group", "text": "T-epitopes", "openItem": "False", "children": [
	    ]}
	]},
	{"tag": "section", "text": "Epitope evaluation", "icon": "bookmark.png", "children": [
	    {"tag": "protocol", "value": "ProtIIITDEvaluations", "text": "default"},
	    {"tag": "protocol", "value": "ProtVaxignMLEpitopeEvaluation", "text": "default"}
	]}
    ]
