"""Output parsing for EpiDope (legacy conda-env runtime)."""

from pathlib import Path

import pandas as pd

from ..constants import (
    EPIDOPE_ACCESSION_COLUMN as ACCESSION_COLUMN,
    EPIDOPE_RAW_COLUMNS as RAW_COLUMNS,
    EPIDOPE_RESIDUE_COLUMN as RESIDUE_COLUMN,
    EPIDOPE_SCORE_COLUMN as SCORE_COLUMN,
)
from .epidope_exceptions import EpiDopeExecutionError

_OUTPUT_COLUMNS = [ACCESSION_COLUMN, RESIDUE_COLUMN, SCORE_COLUMN]


def loadRawScores(resultDir: Path) -> pd.DataFrame:
    """Concatenate the per-accession CSVs EpiDope writes in '<resultDir>/epidope/'.

    One file per input accession, tab-separated, one row per residue. The
    accession is taken from the file stem rather than from a column: EpiDope
    does not repeat it inside the file. Exactly one file is expected, since
    the caller always runs a single sequence per execution.
    """
    perGeneDir = Path(resultDir) / 'epidope'
    csvFiles = sorted(perGeneDir.glob('*.csv'))
    if not csvFiles:
        found = sorted(p.name for p in Path(resultDir).rglob('*') if p.is_file())
        raise EpiDopeExecutionError(
            f"No per-accession score CSV found in '{perGeneDir}'. Files generated by EpiDope: "
            f"{found or '<none>'}."
        )
    if len(csvFiles) > 1:
        raise EpiDopeExecutionError(
            f"More than one score CSV found in '{perGeneDir}' ({[c.name for c in csvFiles]}): the "
            "input FASTA must contain a single sequence."
        )

    frames = []
    for csvPath in csvFiles:
        df = pd.read_csv(csvPath, sep='\t')
        missing = set(RAW_COLUMNS) - set(df.columns)
        if missing:
            raise EpiDopeExecutionError(
                f"Output CSV '{csvPath}' does not contain the expected columns {sorted(missing)}. "
                f"Columns found: {list(df.columns)}."
            )
        df = df.sort_values('position').reset_index(drop=True)
        df.insert(0, ACCESSION_COLUMN, csvPath.stem)
        frames.append(df)

    combined = pd.concat(frames, ignore_index=True)
    combined = combined.rename(columns={'aminoacid': RESIDUE_COLUMN, 'score': SCORE_COLUMN})
    return combined[_OUTPUT_COLUMNS]
