"""Command building and output parsing for ScanNet (legacy conda-env runtime)."""

import glob
from pathlib import Path

import pandas as pd

from ..constants import SCANNET_RAW_CHAIN_COLUMN as RAW_CHAIN_COLUMN, SCANNET_RAW_RESIDUE_COLUMN as RAW_RESIDUE_COLUMN, SCANNET_RAW_SCORE_COLUMN as RAW_SCORE_COLUMN

_OUTPUT_COLUMNS = [RAW_CHAIN_COLUMN, RAW_RESIDUE_COLUMN, RAW_SCORE_COLUMN]


class ScanNetParseError(Exception):
    """The ScanNet output CSV does not match the expected format."""


def build_command(pdbPath: Path, resultDir: Path, name: str) -> str:
    # No 'predict_bindingsites.py'/install_path prefix here: the caller
    # (Plugin.runScanNet) prepends the script name and must set
    # cwd=getScanNetDir() (ScanNet resolves its own 'models/' path relative
    # to the process cwd, not the script's own location -- confirmed
    # reading utilities/paths.py).
    return (
        f'{pdbPath.resolve()} --predictions_folder {resultDir.resolve()} '
        f'--mode epitope --noMSA --pdb --name {name}'
    )


def load_raw_scores(resultDir: Path) -> pd.DataFrame:
    """Locate and load the (single) 'predictions_*.csv' ScanNet writes.

    Located via glob (not the exact reconstructed path,
    ``<name>_single_ScanNet_epitope_noMSA/predictions_<name>.csv``,
    confirmed by reading ScanNet's own source): that subfolder name depends
    on internal details (mode/model-version suffixes) that can change
    between versions.
    """
    csvFiles = sorted(Path(p) for p in glob.glob(str(resultDir / '**' / 'predictions_*.csv'), recursive=True))
    if not csvFiles:
        found = sorted(p.name for p in resultDir.rglob('*') if p.is_file())
        raise ScanNetParseError(
            f"No 'predictions_*.csv' output file found in '{resultDir}'. Files generated by ScanNet: "
            f"{found or '<none>'}."
        )
    if len(csvFiles) > 1:
        raise ScanNetParseError(
            f"More than one output CSV found in '{resultDir}' ({[c.name for c in csvFiles]}): expected exactly one."
        )

    df = pd.read_csv(csvFiles[0])
    missing = {RAW_RESIDUE_COLUMN, RAW_SCORE_COLUMN, RAW_CHAIN_COLUMN} - set(df.columns)
    if missing:
        raise ScanNetParseError(
            f"Output CSV '{csvFiles[0]}' does not contain the expected columns {sorted(missing)}. "
            f"Columns found: {list(df.columns)}."
        )
    return df[_OUTPUT_COLUMNS]
